name: Demo-DBB_Build_on_ZOS_With_GitHub_Actions_SSH
## Notes:
# A sample z/OS DBB workflow using GitHub Actions (GHA) with SSH connection
# Global vars
env:
  # SSH connection information 
  DBB_Host: 'ssh grsrini@3.109.182.248 -p 2022' # A valid SSH account on Z. With pre-generated and tested keys in the runner.
  Clone: 'pipeline-test/ssh-test'
on: workflow_dispatch
jobs:
  Test_SSH:
    runs-on: self-hosted
    steps:
    - name: powershell allow...
        shell:cmd
        run:powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
    - name: check powershell version
        run:$host.Version
    - name: Clone repository
      run: ${{ env.DBB_Host }}
