#Test
name: Demo-DBB_Build_on_ZOS_With_GitHub_Actions_SSH
## Notes:
# A sample z/OS DBB workflow using GitHub Actions (GHA) with SSH connection
# Global vars
env:
# SSH connection information 
DBB_Host: 'ssh grsrini@3.109.182.248 -p 2222' # A valid SSH account on Z. With pre-generated and tested keys in the runner.
on: workflow_dispatch
