#Test
name: Demo-DBB_Build_on_ZOS_With_GitHub_Actions_SSH
## Notes:
# A sample z/OS DBB workflow using GitHub Actions (GHA) with SSH connection
# Global vars
env:
# SSH connection information 
DBB_Host: 'ssh grsrini@3.109.182.248' # A valid SSH account on Z. With pre-generated and tested keys in the runner.
# Pipeline scripts on z/OS (relative to the SSH user's Home Dir in USS) Clone: 'All-pipeline-scripts/git-clone-ssh.sh' # Script to clone the code from GitHub to z/OS DBB_Build: 'All-pipeline-scripts/dbb-build.sh' # Script to perform the DBB build on z/OS
# "on" trigger to manually start this workflow. Can add "pull, push..." for auto trigger.
# see https://docs.github.com/en/actions/learn-github-actions/contexts
on: workflow_dispatch
